const MESSAGE_TX_SYNC = 0xA4;
const DEFAULT_NETWORK_NUMBER = 0x00;

// Configuration messages
const MESSAGE_CHANNEL_UNASSIGN = 0x41;
const MESSAGE_CHANNEL_ASSIGN = 0x42;
const MESSAGE_CHANNEL_ID = 0x51;
const MESSAGE_CHANNEL_PERIOD = 0x43;
const MESSAGE_CHANNEL_SEARCH_TIMEOUT = 0x44;
const MESSAGE_CHANNEL_FREQUENCY = 0x45;
const MESSAGE_CHANNEL_TX_POWER = 0x60;
const MESSAGE_NETWORK_KEY = 0x46;
const MESSAGE_TX_POWER = 0x47;
const MESSAGE_PROXIMITY_SEARCH = 0x71;

// Notification messages
const MESSAGE_STARTUP = 0x6F;

// Control messages
const MESSAGE_SYSTEM_RESET = 0x4A;
const MESSAGE_CHANNEL_OPEN = 0x4B;
const MESSAGE_CHANNEL_CLOSE = 0x4C;
const MESSAGE_CHANNEL_REQUEST = 0x4D;

// Data messages
const MESSAGE_CHANNEL_BROADCAST_DATA = 0x4E;
const MESSAGE_CHANNEL_ACKNOWLEDGED_DATA = 0x4F;
const MESSAGE_CHANNEL_BURST_DATA = 0x50;

// Channel event messages
const MESSAGE_CHANNEL_EVENT = 0x40;

// Requested response messages
const MESSAGE_CHANNEL_STATUS = 0x52;
// const MESSAGE_CHANNEL_ID = 0x51;
const MESSAGE_VERSION = 0x3E;
const MESSAGE_CAPABILITIES = 0x54;
const MESSAGE_SERIAL_NUMBER = 0x61;

// Message parameters
const CHANNEL_TYPE_TWOWAY_RECEIVE = 0x00;
const CHANNEL_TYPE_TWOWAY_TRANSMIT = 0x10;
const CHANNEL_TYPE_SHARED_RECEIVE = 0x20;
const CHANNEL_TYPE_SHARED_TRANSMIT = 0x30;
const CHANNEL_TYPE_ONEWAY_RECEIVE = 0x40;
const CHANNEL_TYPE_ONEWAY_TRANSMIT = 0x50;
const RADIO_TX_POWER_MINUS20DB = 0x00;
const RADIO_TX_POWER_MINUS10DB = 0x01;
const RADIO_TX_POWER_0DB = 0x02;
const RADIO_TX_POWER_PLUS4DB = 0x03;
const RESPONSE_NO_ERROR = 0x00;
const EVENT_RX_SEARCH_TIMEOUT = 0x01;
const EVENT_RX_FAIL = 0x02;
const EVENT_TX = 0x03;
const EVENT_TRANSFER_RX_FAILED = 0x04;
const EVENT_TRANSFER_TX_COMPLETED = 0x05;
const EVENT_TRANSFER_TX_FAILED = 0x06;
const EVENT_CHANNEL_CLOSED = 0x07;
const EVENT_RX_FAIL_GO_TO_SEARCH = 0x08;
const EVENT_CHANNEL_COLLISION = 0x09;
const EVENT_TRANSFER_TX_START = 0x0A;
const CHANNEL_IN_WRONG_STATE = 0x15;
const CHANNEL_NOT_OPENED = 0x16;
const CHANNEL_ID_NOT_SET = 0x18;
const CLOSE_ALL_CHANNELS = 0x19;
const TRANSFER_IN_PROGRESS = 0x1F;
const TRANSFER_SEQUENCE_NUMBER_ERROR = 0x20;
const TRANSFER_IN_ERROR = 0x21;
const MESSAGE_SIZE_EXCEEDS_LIMIT = 0x27;
const INVALID_MESSAGE = 0x28;
const INVALID_NETWORK_NUMBER = 0x29;
const INVALID_LIST_ID = 0x30;
const INVALID_SCAN_TX_CHANNEL = 0x31;
const INVALID_PARAMETER_PROVIDED = 0x33;
const EVENT_QUEUE_OVERFLOW = 0x35;
const USB_STRING_WRITE_FAIL = 0x70;
const CHANNEL_STATE_UNASSIGNED = 0x00;
const CHANNEL_STATE_ASSIGNED = 0x01;
const CHANNEL_STATE_SEARCHING = 0x02;
const CHANNEL_STATE_TRACKING = 0x03;
const CAPABILITIES_NO_RECEIVE_CHANNELS = 0x01;
const CAPABILITIES_NO_TRANSMIT_CHANNELS = 0x02;
const CAPABILITIES_NO_RECEIVE_MESSAGES = 0x04;
const CAPABILITIES_NO_TRANSMIT_MESSAGES = 0x08;
const CAPABILITIES_NO_ACKNOWLEDGED_MESSAGES = 0x10;
const CAPABILITIES_NO_BURST_MESSAGES = 0x20;
const CAPABILITIES_NETWORK_ENABLED = 0x02;
const CAPABILITIES_SERIAL_NUMBER_ENABLED = 0x08;
const CAPABILITIES_PER_CHANNEL_TX_POWER_ENABLED = 0x10;
const CAPABILITIES_LOW_PRIORITY_SEARCH_ENABLED = 0x20;
const CAPABILITIES_SCRIPT_ENABLED = 0x40;
const CAPABILITIES_SEARCH_LIST_ENABLED = 0x80;
const CAPABILITIES_LED_ENABLED = 0x01;
const CAPABILITIES_EXT_MESSAGE_ENABLED = 0x02;
const CAPABILITIES_SCAN_MODE_ENABLED = 0x04;
const CAPABILITIES_PROX_SEARCH_ENABLED = 0x10;
const CAPABILITIES_EXT_ASSIGN_ENABLED = 0x20;
const CAPABILITIES_FS_ANTFS_ENABLED = 0x40;
const TIMEOUT_NEVER = 0xFF;
    
// Power Paging Message IDs
const POWER_PAGE_STANDARD_POWER_ONLY = 0x10;
const POWER_PAGE_TORQUE_EFFECTIVENESS = 0x13;
const POWER_PAGE_MANUFACTURER_INFO = 0x50;
const POWER_PAGE_PRODUCT_INFO = 0x51;
const POWER_PAGE_BATTERY_VOLTAGE = 0x52;
const POWER_PAGE_CALIBRATION_REQUEST = 0x01;